# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rag_backend_development
  username: <%= ENV.fetch("DATABASE_USERNAME") { ENV["USER"] } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: rag_backend_test
  username: <%= ENV.fetch("DATABASE_USERNAME") { ENV["USER"] } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the provided URL does not contain the password, you can also provide it
# separately:
#
#   DATABASE_PASSWORD=mypass
#
# On Rails 8.1+, you can use the encrypted credentials to store the database
# password. See the encrypted credentials guide for more information:
# https://guides.rubyonrails.org/security.html#custom-credentials
#
# On production, you should set DATABASE_URL or configure each of these values
# explicitly:
#
production:
  primary:
    <<: *default
    database: rag_backend_production
    username: rag_backend
    password: <%= ENV["RAG_BACKEND_DATABASE_PASSWORD"] %>
  cache:
    <<: *default
    database: rag_backend_production_cache
    username: rag_backend
    password: <%= ENV["RAG_BACKEND_DATABASE_PASSWORD"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: rag_backend_production_queue
    username: rag_backend
    password: <%= ENV["RAG_BACKEND_DATABASE_PASSWORD"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: rag_backend_production_cable
    username: rag_backend
    password: <%= ENV["RAG_BACKEND_DATABASE_PASSWORD"] %>
    migrations_paths: db/cable_migrate
